name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglu1-mesa-dev

      - name: Set up Flutter packages
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk
      
      - name: Upload Android APK
        uses: actions/upload-artifact@v2
        with:
          name: Android App
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1

      - name: Install dependencies
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -runFirstLaunch

      - name: Set up Flutter packages
        run: flutter pub get

      - name: Build iOS App
        run: flutter build ios --no-codesign

      - name: Upload iOS App
        uses: actions/upload-artifact@v2
        with:
          name: iOS App
          path: build/ios/iphoneos/Runner.app 
